version: '3.7'
services:
  api:
    build:
      context: ./api
      args:
        BUILD_ARGS: main.go
    image: ${IMAGE}

  bot:
    build:
      context: ./api
      args:
        BUILD_ARGS: cmd/bot/*.go
    image: ${IMAGE}

  web:
    build:
      context: ./web
      target: production-stage
    image: ${IMAGE}
